FAST-Mini-Project/front-end

src/components/pagenation/PageNation.module.scss, src/components/pagenation/PageNation.tsx, src/dummy/DummyData.ts, src/pages/admin/Admin.module.scss, src/pages/admin/Admin.tsx, src/pages/admin/AdminAnnual.module.scss, src/pages/admin/AdminAnnual.tsx, src/pages/login/LogIn.tsx, src/pages/login/SignUp.tsx
admin/employee 페이지
- 이름으로 검색 기능 추가
- pagenation 기능 추가
=> feat: admin/employee 페이지, 이름 검색 + pagenation 기능 추가

.eslintrc.cjs, public/DummyAllWork20236.json, public/DummyAllWork20237.json, src/components/common/MainHeader.module.scss, src/components/common/MainHeader.tsx, src/components/main/AnnualApplyModal.module.scss, src/components/main/AnnualApplyModal.tsx, src/components/main/CalendarForm.module.scss, src/components/main/CalendarForm.tsx, src/index.scss, src/layout/MainLayout.module.scss, src/types/MainTypes.ts
+ [#11] feat : 로그아웃 링크 추가
+ [#11] setting: eslintrc any타입 오류 캐치 x
+ [#1] feat: 메인페이지 모달 스타일 추가 기능구현x
=> Feat/headerfooter #11

public/DummyAllAnnual20237.json, src/components/common/MainHeader.module.scss, src/components/main/AnnualApplyModal.module.scss, src/components/main/AnnualApplyModal.tsx, src/components/main/CalendarForm.tsx, src/utils/CalendarUtils.ts
+ [#1] feat: 내 연차/당직, 전체 연차/당직 필터링 기능 추가
+ [#11] style: 마이페이지, 로그아웃 사이 | 위치 수정
+ [#1] feat : 연차 신청 기능 구현 (cookie에 access토큰 있어야 가능할듯) 틀만 잡기.
=> Feat/main #1

src/_variables.scss, src/components/adminwork/AdminWork.module.scss, src/components/adminwork/AdminWork.tsx, src/pages/admin/AdminDuty.module.scss, src/pages/admin/AdminDuty.tsx
admin/duty 페이지 작성
admin/duty 페이지에 사용할 admin/work 모달 작성
=> feat:admin/duty 페이지 1차 작성

src/api/admin/index.ts, src/api/index.ts, src/api/main/index.ts, src/api/mypage/index.ts, src/api/user/index.ts, src/types/AccessTypes.ts, src/utils/cookie.ts
api 요청 코드를 작성했습니다. 수정이 필요하시면 수정하셔도 되고, 가져다 쓰셔도 될 것 같습니다. 이제 테스트 진행하면서 데이터 연결해보겠습니다!
=> [#27] feat: api 요청코드 작성

src/api/admin/index.ts, src/api/mypage/index.ts, src/api/user/index.ts, src/pages/main/Main.tsx
api 요청에서 token을 사용할 때, 
`Bearer ${token}`
으로 수정했습니다.
=> [#27] fix: api 토큰 이슈 해결

src/components/mypage/ApprovedAnnual.module.scss, src/components/mypage/ApprovedAnnual.tsx, src/components/mypage/RequestedAnnual.module.scss, src/components/mypage/RequestedAnnual.tsx
[#4] feat: MyPage 연차 조회 탭 누락 스타일링 추가
=> feat: MyPage 연차 조회 탭 누락 스타일링 추가

src/api/main/index.ts, src/components/common/MainHeader.tsx, src/components/main/AnnualApplyModal.tsx, src/utils/PrivateRoute.tsx
+ 관리자페이지 - 메인페이지 접근 시 예외처리
+ ApplyAnnual api 틀 잡아놓음
=> Feat/apply annual #31

src/components/mypage/ApprovedAnnual.module.scss, src/components/mypage/CompletedDutyList.module.scss, src/components/mypage/MonthRange.module.scss, src/components/mypage/PlannedDutyList.module.scss, src/components/mypage/RequestedAnnual.module.scss
[#18] Style: MyPage 연차 및 당직 조회 탭 스크롤, 스타일링 통일
=> [#18] Style: MyPage 연차 및 당직 조회 탭 스크롤, 스타일링 통일

src/components/mypage/ApprovedAnnual.module.scss, src/components/mypage/CompletedDutyList.module.scss, src/components/mypage/MonthRange.module.scss, src/components/mypage/PlannedDutyList.module.scss, src/components/mypage/RequestedAnnual.module.scss
[#4] style: MyPage 연차 및 당직 조회 탭 스크롤, 스타일링 통일
=> [#4] style: MyPage 연차 및 당직 조회 탭 스크롤, 스타일링 통일

src/api/main/index.ts
Merge #41 작업 내용과 Merge #42, #43 작업 내용 병합 중
에러로 병합되지 않은 내용을 다시 push 합니다!
=> fix: 관리자 페이지, 비로그인 시 예외처리 병합오류 수정

src/api/main/index.ts, src/components/main/CalendarForm.tsx
- 메인페이지 내 연차 /당직 조회 필터링 이슈 해결
- 연차 조회 api 잘못 작성되어있던 것 fix
- 오늘 포함 이전 날짜 연차 신청 안되게 분기처리
=> [#1] feat: main필터링 문제 및 연차 조회api fix, 오늘 이전 연차 신청x

src/components/mypage/ApprovedAnnual.module.scss, src/components/mypage/RequestedAnnual.module.scss, src/pages/mypage/MyAnnual.module.scss, src/pages/mypage/MyAnnual.tsx, src/pages/mypage/MyPage.module.scss, src/pages/mypage/Mypage.tsx
[#4] style: MyPage main 태그 삭제, 연차 조회 탭 디테일 스타일링 변경
=> style: MyPage main 태그 삭제, 연차 조회 탭 디테일 스타일링 변경

src/components/mypage/ApprovedAnnual.module.scss, src/components/mypage/CompletedDutyList.module.scss, src/components/mypage/MenuTab.module.scss, src/components/mypage/PlannedDutyList.module.scss, src/components/mypage/RequestedAnnual.module.scss, src/pages/mypage/MyAnnual.module.scss, src/pages/mypage/MyAnnual.tsx, src/pages/mypage/MyDuty.module.scss, src/pages/mypage/MyDuty.tsx, src/pages/mypage/MyPage.module.scss, src/pages/mypage/Mypage.tsx
[#18] style: MyPage MenuTab height 고정, 연차 및 당직 조회 탭 정렬 및 디테일 스타일링
=> style: MyPage MenuTab height 고정, 연차 및 당직 조회 탭 정렬 및 디테일 스타일링

src/api/user/index.ts, src/pages/login/LogIn.module.scss, src/pages/login/LogIn.tsx, src/pages/login/SignUp.module.scss, src/pages/login/SignUp.tsx, src/utils/constants/regex.ts
- 프론트측 로그인 유효성 검사 코드를 작성했습니다.
- 비밀번호는 원래 8자 이상인데, 더미 계정 로그인을 위해 우선 4자로 지정했습니다.
=> Feat/input validation #49

src/api/admin/index.ts, src/components/adminfilter/AdminFilter.tsx, src/components/adminwork/AdminWork.tsx, src/layout/AdminLayout.tsx, src/pages/admin/AdminAnnual.module.scss, src/pages/admin/AdminAnnual.tsx
관리자 권한 api 추가 
adminannual 정렬 함수 변경
=> Feat/admin/api 관리자 권한 api 추가 + 기타 수정

src/App.tsx, src/api/admin/index.ts, src/api/user/index.ts, src/components/common/MainHeader.tsx, src/components/main/CalendarForm.tsx, src/layout/AdminLayout.tsx, src/layout/AdminPrivateRouteWrapper.tsx, src/utils/PrivateRoute.tsx
관리자 권한 api 라우트 단에서 막도록 수정했습니다!
기존 PrivateRoute에서는 비동기함수를 사용할 수 없어서, 새로 tsx파일에 넣고 작성했습니다
정상 작동 확인했는데, 혹시나 문제 발생 시 말씀해주세요
alert는 두번 뜨는데, React Strict모드라 그런거 같기도해서, 배포 해보고 문제 지속되면 해결하도록 하겠습니다.
=> Feat/admin redirect #53

src/api/user/index.ts, src/utils/handleLogout.ts
토큰 만료시 로그아웃 api가 동작을 못해서 
토큰이 쿠키 남아있는 현상을 제거
=> feat/logout: 토큰 만료시 토큰이 남아있는 문제 해결?

src/api/mypage/index.ts, src/components/mypage/ApprovedAnnual.module.scss, src/components/mypage/ApprovedAnnual.tsx, src/components/mypage/CompletedDutyList.module.scss, src/components/mypage/CompletedDutyList.tsx, src/components/mypage/MenuTab.module.scss, src/components/mypage/MenuTab.tsx, src/components/mypage/MonthRange.module.scss, src/components/mypage/MonthRange.tsx, src/components/mypage/PlannedDutyList.module.scss, src/components/mypage/PlannedDutyList.tsx, src/components/mypage/RemainingAnnual.module.scss, src/components/mypage/RemainingAnnual.tsx, src/components/mypage/RequestedAnnual.module.scss, src/components/mypage/RequestedAnnual.tsx, src/pages/mypage/MyAnnual.module.scss, src/pages/mypage/MyAnnual.tsx, src/pages/mypage/MyDuty.module.scss, src/pages/mypage/MyDuty.tsx, src/pages/mypage/MyInfo.module.scss, src/pages/mypage/MyInfo.tsx, src/pages/mypage/Mypage.tsx, src/types/MypageTypes.ts
=> [#47] feat: MyPage 비밀번호 수정 기능 구현 및 api 연동

src/api/mypage/index.ts, src/components/mypage/ApprovedAnnual.module.scss, src/components/mypage/ApprovedAnnual.tsx, src/components/mypage/MenuTab.module.scss, src/components/mypage/MenuTab.tsx, src/components/mypage/MonthRange.module.scss, src/components/mypage/MonthRange.tsx, src/components/mypage/RemainingAnnual.module.scss, src/components/mypage/RemainingAnnual.tsx, src/components/mypage/RequestedAnnual.module.scss, src/components/mypage/RequestedAnnual.tsx, src/pages/mypage/MyAnnual.module.scss, src/pages/mypage/MyAnnual.tsx, src/pages/mypage/Mypage.tsx, src/types/MypageTypes.ts
- 개인 연차 조회, 연차 취소/ 취소 신청 api 연동
- MyPage 연차 조회 탭, 신청 및 승인 연차 리스트 스타일 변경
- 잔여 연차 갯수, MonthRange 위치 및 기능, 스타일 변경
=> [#45] feat, style: MyPage 개인 연차 조회, 연차 취소/ 취소 신청 api 연동 및 스타일 변경

src/api/mypage/index.ts, src/components/mypage/ApprovedAnnual.module.scss, src/components/mypage/ApprovedAnnual.tsx, src/components/mypage/CompletedDutyList.module.scss, src/components/mypage/CompletedDutyList.tsx, src/components/mypage/MenuTab.module.scss, src/components/mypage/MenuTab.tsx, src/components/mypage/MonthRange.module.scss, src/components/mypage/MonthRange.tsx, src/components/mypage/PlannedDutyList.module.scss, src/components/mypage/PlannedDutyList.tsx, src/components/mypage/RemainingAnnual.module.scss, src/components/mypage/RemainingAnnual.tsx, src/components/mypage/RequestedAnnual.module.scss, src/components/mypage/RequestedAnnual.tsx, src/pages/mypage/MyAnnual.module.scss, src/pages/mypage/MyAnnual.tsx, src/pages/mypage/MyDuty.module.scss, src/pages/mypage/MyDuty.tsx, src/pages/mypage/Mypage.tsx, src/types/MypageTypes.ts
- 개인 당직 조회 api 연동
- 당직 조회 탭, 예정 및 완료 당직 리스트 스타일 변경
=> [#46] feat, style: MyPage 개인 당직 조회 api 연동 및 스타일 변경

package-lock.json, package.json, src/App.tsx, src/index.scss
=> Feat/code splitting #64

src/components/common/MainHeader.tsx
=> [#66] refactor: 오타수정

src/api/mypage/index.ts, src/components/loginSignupRegex/regexValid.tsx, src/components/main/AnnualApplyModal.tsx, src/components/main/CalendarForm.tsx, src/pages/login/SignUp.tsx, src/types/MainTypes.ts, src/utils/constants/regex.ts
+ 연차 신청 예외처리를 진행했습니다. 이제 어제 날짜부터 신청이 안되며, 신청된 나의 연차가 하나라도 있을 때(status구분 x) 신청 모달이 나오지 않습니다. 그리고 나의 연차가 15개 신청되있는 상태에서도 신청이 불가합니다!
+ 로그인 / 회원가입 유효성 검사 코드를 작성, 유저이름을 추가적으로 유효성 검사 처리했습니다.
=> Feat/headermain refactor #66

src/pages/mypage/MyInfo.module.scss, src/pages/mypage/MyInfo.tsx
[#47] feat, style: MyInfo 비밀번호 수정 탭 유효성 검사 추가, 공통 스타일 적용
=> feat, style: MyInfo 비밀번호 수정 탭 유효성 검사 추가, 공통 스타일 적용

src/components/mypage/RemainingAnnual.tsx
[#45] feat: MyAnnual 잔여 연차 갯수 로직 변경(신청, 승인 통합)
=> feat: MyAnnual 잔여 연차 갯수 로직 변경(신청, 승인 통합)

src/pages/admin/AdminAnnual.tsx, src/pages/admin/AdminEmployee.tsx, src/utils/SortedData.ts
utils/sorteddata.ts에서 꺼내 쓰는 함수로 변경
=> refacto:admin 정렬 함수 통일
